### PR TITLE
resolve multiple thread blocks in proof cache

### PR DESCRIPTION
**Pull request by i-walker**
This initial draft refactors the cache as a member of the compilerContext.

### CODE REVIEW

**Comment by raulraja** [comment]
We'll merge once the test is ignored, thanks @i-walker !

**Comment by i-walker** [comment]
Ignores. the gradle ide test and addresses https://github.com/arrow-kt/arrow-meta/issues/695 in the patch

**Comment by rachelcarmena** [comment]
@i-walker , bud, I've reverted the last commit to be able to merge with `master` branch in a few minutes :raised_hands:

**Comment by rachelcarmena** [comment]
:green_apple: Merged!

**Comment by i-walker** [comment]
Thanks. a lot @rachelcarmena

**Pull request merged**
