### PR TITLE
[Analysis] Primitive types

### PR DESCRIPTION
**Pull request by serras**
This PR completes the support for primitive types in Kotlin, adding all the required special cases.

### CODE REVIEW

**Comment by 47degdev** [comment]
Task linked: [CU-12gwav4 Handle primitive types](https://app.clickup.com/t/12gwav4)

**Comment by 47degdev** [comment]
Task linked: [CU-1je1mjf Handle simple "when" in constraint collection](https://app.clickup.com/t/1je1mjf)

**Comment by serras** [comment]
I forgot to branch and included here also the code relative to handling `when` in constraint collection :/

**Review by raulraja — APPROVED** [review]
thanks @serras !

**Pull request merged**
