### PR TITLE
[Analysis] SARIF output for analysis errors

### PR DESCRIPTION
**Pull request by raulraja**
Generates a SARIF file for each module analyzed if there were any errors.
This PR is the first step toward getting arrow analysis integrated into GitHub comments and GitHub code analysis.
In another PR, I discussed with @JavierSegoviaCordoba creating a GitHub action for arrow analysis that [pushes these results to the PRs](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github).

@serras This is currently not being generated for the java plugin because I'm not sure where it's the best place to notify the solver state that the module has finished processing so it can go ahead and create the SARIF file. Additionally, there is a new file [ErrorIds](https://github.com/arrow-kt/arrow-meta/pull/948/files#diff-3ce37c9f27215ebfc74ff2209f6b1a45090778a346a9b240ada00bf2c1560d26) Where we can include short descriptions for each error type, so they are displayed correctly in Github.

We still need to figure out how to statically obtain the plugin version programmatically so we can pass it to the file. 

A generated Sarif file for one of the tests looks like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "results": [
        {
          "level": "error",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/var/folders/3g/zgtzwm_90zx5n8d3s1685b1w0000gn/T/Kotlin-Compilation4123756779864608913/sources/Source.kt"
                },
                "region": {
                  "startColumn": 20,
                  "startLine": 20
                }
              }
            }
          ],
          "message": {
            "text": "pre-condition `x is 42` is not satisfied in `bar(1)`\n  -> unsatisfiable constraint: `1 == 42`\n  -> `1` bound to param `x` in `test.bar` at /var/folders/3g/zgtzwm_90zx5n8d3s1685b1w0000gn/T/Kotlin-Compilation4123756779864608913/sources/Source.kt: (15, 15):\n  -> main function body"
          },
          "ruleId": "arrow.analysis.UnsatCallPre"
        },
        {
          "level": "error",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/var/folders/3g/zgtzwm_90zx5n8d3s1685b1w0000gn/T/Kotlin-Compilation4123756779864608913/sources/Source.kt"
                },
                "region": {
                  "startColumn": 20,
                  "startLine": 20
                }
              }
            }
          ],
          "message": {
            "text": "pre-condition `x is 42` is not satisfied in `bar(1)`\n  -> unsatisfiable constraint: `1 == 42`\n  -> `1` bound to param `x` in `test.bar` at /var/folders/3g/zgtzwm_90zx5n8d3s1685b1w0000gn/T/Kotlin-Compilation4123756779864608913/sources/Source.kt: (15, 15):\n  -> main function body"
          },
          "ruleId": "arrow.analysis.UnsatCallPre"
        }
      ],
      "tool": {
        "driver": {
          "downloadUri": "https://arrow-kt.io/docs/meta/analysis-quickstart.html",
          "fullName": "Arrow Analysis",
          "informationUri": "https://arrow-kt.io/docs/meta/analysis-quickstart.html",
          "language": "en",
          "name": "Arrow Analysis",
          "organization": "arrow-kt",
          "rules": [
            {
              "helpUri": "https://arrow-kt.io/docs/meta/analysis/UnsatCallPre.html",
              "id": "UnsatCallPre",
              "name": "UnsatCallPre",
              "shortDescription": {
                "text": "`UnsatCallPre` (attached to the argument): The required pre-conditions for a (method,\nproperty, function) call are not satisfied.\n\nFor example:\n\n```kotlin\n  val wrong = 1 / 0  // does not satisfy '0 != 0' in Int.div law\n```"
              }
            },
            {
              "helpUri": "https://arrow-kt.io/docs/meta/analysis/UnsatCallPre.html",
              "id": "UnsatCallPre",
              "name": "UnsatCallPre",
              "shortDescription": {
                "text": "`UnsatCallPre` (attached to the argument): The required pre-conditions for a (method,\nproperty, function) call are not satisfied.\n\nFor example:\n\n```kotlin\n  val wrong = 1 / 0  // does not satisfy '0 != 0' in Int.div law\n```"
              }
            }
          ],
          "semanticVersion": "1.0.0",
          "version": "1.0.0"
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by serras** [comment]
@raulraja unfortunately Javac works file by file, and it doesn't provide a single "everything is finished" event. One possibility is to keep a (growing) list of SARIF information and dump if *on every* single "finished `ANALYZE`" event (that is, when we finish our own analysis).

**Comment by raulraja** [comment]
@serras I agree, I dislike the duplication as well, the issue I faced was adding this to a common place where it would end up being used by all compiler plugins without having to reimplement it on each one. I was not also sure if all errors had to be reported in SARIF like in the case of unknown errors when parsing. I will look and see if I can make it so the duplication is gone but we preserve a single impl for all compiler plugins.

**Comment by raulraja** [comment]
@serras addressed your comments and rearranged so impl provide `handleError,` also made it work in Java by sending the build folder as compiler plugin arg to javac

**Review by serras — APPROVED** [review]

**Comment by serras** [comment]
@raulraja I think we are ready to merge now

**Pull request merged**
