### PR TITLE
Fix dependencies for Java SMT and Z3

### PR DESCRIPTION
**Pull request by rachelcarmena**
@i-walker , mate, please, try this configuration :raised_hands:

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Checks are green now after some fixes :wink:

**Comment by rachelcarmena** [comment]
@i-walker , is Z3 solver necessary? Other solvers like `PRINCESS` works. For instance:

```
  println(ctx(SolverContextFactory.Solvers.PRINCESS).version)
```

prints:

```
Princess (2019-11-20 (assertionless))
```

However, solvers like `Z3` or `MathSAT` (native solvers) require native libraries so it's necessary to install them in the OS.

**Comment by i-walker** [comment]
Thanks @rachelcarmena ! 😄 My cache was in a weird state.

**Comment by rachelcarmena** [comment]
Great, happy for it :raised_hands:

**Pull request merged**
