### PR TITLE
Add Intellij Plugin Verifier execution

### PR DESCRIPTION
**Pull request by rachelcarmena**
# Context

**Arrow Meta IDEA Plugin** must be compatible with the same versions as **Kotlin Plugin** for Intellij IDEA.

For Kotlin `1.3.61` and Intellij IDEA `2019.3.5`: 
* Kotlin Plugin 1.3.61-release-IJ2019.3-1

That [Kotlin Plugin](https://plugins.jetbrains.com/plugin/6954-kotlin/update/73175) version:
* Since build: `193.3793.14`
* Until build: `201.*`

The first build is not available to download so we'll focus on the correspondent versions to those builds:

* Since version: `2019.3.5`
* Until version: `2020.1.1`

# Report by Jetbrains

compatibility-issues

These compatibility issues can be discovered through:
* `verifyPlugin` Gradle task
* [Intellij Plugin Verifier](https://github.com/JetBrains/intellij-plugin-verifier)

## Configuration defects

Configuration defects are obtained through `verifyPlugin` Gradle task. The first result was:

```
Description is too short
Plugin descriptor plugin.xml does not include any module dependency tags. The plugin
   is assumed to be a legacy plugin and is loaded only in IntelliJ IDEA.
```

However, I solved the first one and it doesn't appear now.

See [Verify configuration step](https://github.com/arrow-kt/arrow-meta/runs/674076264?check_suite_focus=true).

## Compatibility issues with "since" version

See [Verify 'since' step](https://github.com/arrow-kt/arrow-meta/runs/674076264?check_suite_focus=true).

## Compatibility issues with "until" version

See [Verify 'until' step](https://github.com/arrow-kt/arrow-meta/runs/674076264?check_suite_focus=true).

# Proposal

The compatibility issues list is huge now so a proposal would be to merge this pull request and to solve the issues in other pull requests.

When the list has disappeared or just a few items, I'll update the GitHub Actions to write the report as a comment in every pull request.

To solve **compatibility issues with "until" version**, #606 must be merged before.

Meanwhile, **compatibility issues with "since" version** can be solved.

### CODE REVIEW

**Comment by i-walker** [comment]
Thanks, @rachelcarmena I'll try to resolve some of those issues, as #606 gets merged.

**Comment by i-walker** [comment]
@rachelcarmena , please don't update the version

**Comment by rachelcarmena** [comment]
> Thanks, @rachelcarmena I'll try to resolve some of those issues, as #606 gets merged.

Thanks!! :raised_hands: **Configuration defects** and **compatibility issues with 'since' version** can be fixed meanwhile.

**Comment by rachelcarmena** [comment]
> @rachelcarmena , please don't update the version

It's just `2019.3.4` to `2019.3.5`.

It doesn't require changes and it's consistent with the Kotlin Plugin. 

Let's merge this pull request and create other pull requests to fix the issues.

**Comment by rachelcarmena** [comment]
I'll propose the upgrade in another PR and another one to skip the flaky test.

**Comment by rachelcarmena** [comment]
This is already ready to be reviewed and merged :+1: 

I'll add more features when compatibility issues are solved or reduced :raised_hands:

**Pull request merged**
