### PR TITLE
[Analysis] Kotlin 1.6.0-M1 support

### PR DESCRIPTION
**Pull request by serras**
This PR makes the necessary changes for Arrow Meta to compile both in 1.5.31 and 1.6.0-M1. Note that it's a PR against #876 because it was useless to update `IrInterpreter` to remove it aftwerwards.

In addition, the GitHub Action is now configured to check against the two Kotlin versions, and also against Java targets 1.9 and 11.

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]
Really nice!! 👏 👏 👏

**Review by raulraja — APPROVED** [review]
thanks @serras !

**Comment by serras** [comment]
@raulraja @nomisRev  it seems that the "old" `build_artifacts` will remain as "waiting" until everything is merged in `main`. However, I cannot merge because I have no permissions, could you any of you do so?

**Comment by nomisRev** [comment]
@serras it's green 🥳
I noticed when changing Github Actions sometimes it tries to look for an old version of the job as a `required` step. This means we have to force merge (admin).

We can also temporarily remove the `build_artifacts` requirement.

**Comment by nomisRev** [comment]
Just saw your message. I will remove `build_artifacts` for now as a requirement, because all subsequent PRs will have the same issue afaik.

We have also removed this requirement in Arrow for the same reason atm. I cannot re-add new requirements there :/

**Pull request merged**
