### PR TITLE
reencode Services

### PR DESCRIPTION
**Pull request by i-walker**
adds a better encoding for project and application services.
```kotlin
addProjectService(
  service = MyService::class.java,
  instance = { project: Project, hijackedService: MyService? ->
    object : MyService {
      override fun printLn(f: KtNamedFunction): Unit =
        println("Function: ${f.name} returns ${f.resolveToDescriptorIfAny()?.returnType ?: "ERROR"}")
    }
  }
)
```
This algebra also provides the hijacked services from 3rd parties, given that the services has been instatiated by a plugn one depends.
- [X] add ModuleListener
- [x] update Docs

### CODE REVIEW

**Comment by i-walker** [comment]
Please don't merge until Docs have been updated.

**Comment by i-walker** [comment]
Docs have been updated :)

**Comment by raulraja** [comment]
Merge when this is resolved please https://github.com/arrow-kt/arrow-meta/pull/534/checks?check_run_id=580404605#step:5:61893

**Comment by i-walker** [comment]
Thanks @rachelcarmena  🎉 👍

**Pull request merged**
