### PR TITLE
[WIP] Add whitespace as separator for annotations

### PR DESCRIPTION
**Pull request by paranoidmonoid**
Fix for https://github.com/arrow-kt/arrow-meta/issues/893

Add a whitespace as a separator for `@annotations` in `ClassOrObject`

### CODE REVIEW

**Comment by paranoidmonoid** [comment]
@raulraja Do you have the guidelines about testing the changes? Also, i noticed that the same issue is potentially in `File`, `ModifierList` and `AnnotatedExpression`.

Should I include them in this PR, too?

**Comment by raulraja** [comment]
@paranoidmonoid thanks for the PR! . These kinds of issues can be tested similar to how it is done in https://github.com/arrow-kt/arrow-meta/blob/main/libs/arrow-meta/src/test/kotlin/arrow/meta/quotes/scope/templates/IfExpressionTest.kt

You create a plugin that does the transformation that you want to test and a compiler test where the plugin is applied and you assert things like if it compiles, the output contains certain words or a program after processed produces a value.

**Comment by serras** [comment]
@paranoidmonoid thanks for sending the fix in! I've taken the liberty of merging with the latest `main` and running the formatter; otherwise the build fails on a preliminary step and tests don't really run (btw, you can run the formatting yourself by using `gradle spotlessKotlinApply`).

**Comment by serras** [comment]
I've taken a look at this and it turned out that more annotations had this problem, so thanks for catching this for us, @paranoidmonoid. Once the CI passes, I'll merge :)

**Review by serras — APPROVED** [review]

**Pull request merged**
