### PR TITLE
update ide to 2020.1

### PR DESCRIPTION
**Pull request by i-walker**
Note: the gradle tests are failing
I may need help from @jansorg to resolve them.

### CODE REVIEW

**Comment by i-walker** [comment]
Be advised not to merge a commit from master into this branch until master is green.

**Comment by rachelcarmena** [comment]
> Be advised not to merge a commit from master into this branch until master is green.

Solved via #618 (I explained the reason there).

**Comment by rachelcarmena** [comment]
@i-walker , please, it would be necessary to update this PR with `master` branch.

Otherwise, #625 by @jansorg (PR on this branch) doesn't execute the Intellij Plugin Verification.

Thanks!!

**Comment by rachelcarmena** [comment]
Order:

- First: #627 on `ja-gradle-2020.1` branch by me
- Second:  #625 on `ide-update` branch by J. Arsorg
- Third: #606 on `master` branch by Imran

Teamwork :raised_hands:

**Pull request merged**
